
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Release.Name}}-{{.Values.metadata.name}}
  {{- range $key,$value := .Values.metadata.labels}}
    {{ $key}} : {{$value | quote}}
    Release: {{$.Release.Name}}-{{$value}}
  {{- end}}
  name: {{.Release.Name}}-{{.Values.metadata.name}}
spec:
  ports:
  - name: bakehouseport
    port: {{.Values.service.port}}
    protocol: TCP
    targetPort: {{.Values.service.targetPort}}
  selector:
    app: bakehouse
  type: {{.Values.service.type}}